# uuidv5 generates a name-based UUID, as described in RFC 4122 section 4.3, also known as a "version 5" UUID.

# Unlike the pseudo-random UUIDs generated by uuid, name-based UUIDs derive from namespace and an name, producing the same UUID value every time if the namespace and name are unchanged.

locals {
  uuidv5_namespace = "dns"
  uuidv5_name      = "www.terraform.io"
}

output "uuidv5_output" {
  value = uuidv5(local.uuidv5_namespace, local.uuidv5_name)
}